openapi:  
  hideReplay: true
  codeSamples:
    skipOptionalParameters: true
    languages:
      - lang: 'curl'
        label: 'cURL'
markdown:
  frontMatterKeysToResolve: ['screen-recordings', 'image', 'links']
  lastUpdatedBlock:
    format: long
    locale: en-US
  toc:
    header: Page sections
    depth: 3
  editPage:
    baseUrl: 'https://github.com/Redocly/redocly-cli/tree/main/docs'
    hide: false
navbar:
  items:
    - page: docs/zample.md
      label: Home      
    - page: example-page.md
      label: Link with icon
    - label: Redocly docs
      href: 'https://redocly.com/docs'
search:
  hide: true
