openapi:  
  showExtensions: true
  jsonSamplesExpandLevel: 6
  codeSamples:
    skipOptionalParameters: true
    languages:
      - lang: 'curl'
        label: 'cURL'
      # - lang: 'JavaScript'
      #   label: 'JS'

ignore:
  - CONTRIBUTING.md

theme:
  openapi:
    showChangeLayoutButton: false    
    disableSearch: true
    hideDownloadButton: true
    hideInfoMetadata: true
  sidebar:    
    separatorLine: true
  feedback: 
    hide: true
  typography:
    fontSize: "19px"
    fontFamily: "DM Sans, sans-serif"
  html:
    head:
      links:
        - rel: "stylesheet"
          href: "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap"
