openapi:  
  showExtensions: true
  jsonSamplesExpandLevel: 6
  codeSamples:
    skipOptionalParameters: true
    languages:
      - lang: 'curl'
        label: 'cURL'
      # - lang: 'JavaScript'
      #   label: 'JS'

ignore:
  - CONTRIBUTING.md

navbar:
  items:
    - page: docs/zample.md
      label: Home      
    - page: example-page.md
      label: Link with icon
    - label: Redocly docs
      href: 'https://redocly.com/docs'
search:
  hide: true
